export const ROUTES = {
  SIGNUP: "/SignUp",
  SIGNIN: "/SignIn",
  HOME: "/Home",
  PRODUCTS: "/Products",
  PRODUCT_DETAILS: "/Products/:id",
  INTRODUCE: "/Introduce",
  NEWS: "/News",
  SERVICES: "/Services",
  CONTACTUS: "/ContactUs",
  CART: "/Cart",
  PAYMENT: "/Payment",
  INFORMATION: "/Information",
  USERACCOUNTDETAIL: "/userAccount/:id",
  ORDERHISTORY: "/Payment/:id",
  ADMIN: "/Admin",
  ADMIN_DETAILS: "/Admin?branch=products/:id",
};
